# Generated by Django 4.1.1 on 2022-09-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "eid",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("CPU", "Cpu"),
                            ("Keyboard", "Keyboard"),
                            ("Monitor", "Monitor"),
                            ("Mouse", "Mouse"),
                            ("Printer", "Printer"),
                            ("Projector", "Projector"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_no", models.CharField(max_length=25)),
                ("brand", models.CharField(max_length=30)),
                ("price", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessory_type", models.CharField(max_length=50)),
                ("model_no", models.CharField(max_length=25)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.asset",
                    ),
                ),
            ],
        ),
    ]
