# Generated by Django 4.1.1 on 2022-09-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
