# Generated by Django 4.1.1 on 2022-09-20 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="dtm_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="DTM Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accessory",
            name="dtm_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
        ),
        migrations.AddField(
            model_name="asset",
            name="dtm_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="DTM Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="dtm_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
        ),
    ]
