# Generated by Django 4.1.1 on 2022-09-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_accessory_dtm_created_accessory_dtm_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="management.user",
            ),
        ),
    ]
