# Generated by Django 4.1.1 on 2022-09-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_asset_brand_alter_asset_model_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="accessory_type",
            field=models.CharField(max_length=50, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management.asset",
                verbose_name="Accessory of",
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="model_no",
            field=models.CharField(max_length=25, verbose_name="Model Number"),
        ),
    ]
